name: "automatically-merge"

on:
  push:
    branches: ["master"]

jobs:
  check-merged:
    runs-on: ["ubuntu-latest"]
    steps:
      #1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      - name : detect changed file
        run: |
          # 최신으로 변경 된 파일 중 txt 파일만 출력
          TXTFILES=$(git diff-tree --no-commit-id --name-only --diff-filter=AM -r HEAD | grep "txt$")
          echo "변경된 txt 파일 출력 : "
          echo "$TXTFILES"