name: "automatically-merge"

on:
  push:
    branches: ["master"]

jobs:
  check-merged:
    runs-on: ["ubuntu-latest"]
    steps:
      #1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name : detect changed file
        run: |
          # 최신으로 변경 된 파일 중 txt 파일만 출력
          echo "Changed files in the latest commit: "
          CHANGEDFILES=$(git diff --name-only HEAD~1 HEAD | grep "txt$")
          echo CHANGEDFILES