name: "automatically-merge"

on:
  push:
    branches: ["master"]

jobs:
  check-merged:
    runs-on: ["ubuntu-latest"]
    outputs:
      file_list: ${{ steps.detect_change_file_list.outputs.file_list }}
    steps:
      #1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name : detect changed file
        id: detect_change_file_list
        run: |
          # 최신으로 변경 된 파일 중 txt 파일만 출력
          echo "Changed files in the latest commit: "
          CHANGEDFILES=$(git diff --name-only HEAD~1 HEAD | grep "txt$")
          echo $CHANGEDFILES


          # 부모 디렉토리 경로만 출력
          FOLDER_PATHS=$(echo "$CHANGEDFILES" | xargs -n1 dirname)
          echo "부모 디렉토리 경로 출력 : "
          echo "$FOLDER_PATHS"

          FILE_LIST_JSON=$(echo "$FOLDER_PATHS" | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "output 정리"
          echo "$FILE_LIST_JSON"

          
          echo "::set-output name=file_list::$FILE_LIST_JSON"


  deploy:
    runs-on: ["ubuntu-latest"]
    needs: check-merged
    strategy:
      matrix:
        file_path: ${{fromJson(needs.check-merged.outputs.file_list)}}
    steps:
      - name: test
        run: |
          echo "${{ matrix.file_path}}"
