name: "automatically-merge"

on:
  push:
    branches: ["master"]

jobs:
  check-merged:
    runs-on: ["ubuntu-latest"]
    steps:
      #1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
