name: "automatically-merge"

on:
  push:
    branches: ["master"]

jobs:
  check-merged:
    runs-on: ["ubuntu-latest"]
    steps:
      #1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      - name : detect changed file
        run: |
          # 최신으로 변경 된 파일 중 txt 파일만 출력
          TXTFILES=$(git log -1 --name-only --pretty="" | grep "txt$")
          echo "변경된 도커 파일 출력 : "
          echo "$TXTFILES"
        
          # 부모 디렉토리 경로만 출력
          FOLDER_PATHS=$(echo "$TXTFILES" | xargs -n1 dirname)
          echo "부모 디렉토리 경로 출력 : "
          echo "$FOLDER_PATHS"
